image: privacybydesign/node_yarn:latest

stages:
  - build

before_script:
  - set -euxo pipefail
  - yarn install

build-en:
  stage: build
  script:
    - yarn run grunt build --language="en"
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - build/*

build-nl:
  stage: build
  script:
    - yarn run grunt build --language="nl"
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - build/*
